version: '3.2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: elasticsearch
        environment:
            - network.host=0.0.0.0
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - node.name=cluster1-node1
            - xpack.license.self_generated.type=basic
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # - http.host=0.0.0.0
            # - http.port=9200
            # - "http.cors.allow-origin=\*"
            # - "http.cors.enabled=true"
            # - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
            # - "http.cors.allow-credentials=true"

        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata2:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - 9292:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        depends_on:
            - elasticsearch

volumes:
    esdata2:
        driver: local
